name: ingilizce_app1
description: Faz 1 MVP - Supabase tabanli Ingilizce kelime ogrenme uygulamasi
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  supabase_flutter: ^2.8.4
  http: ^1.2.2
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
