name: passagetr_v2_workspace
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - apps/student_app
  - apps/admin_console
  - packages/shared_core
  - packages/shared_domain
  - packages/shared_data
  - packages/shared_ui
