name: shared_data
description: PASSAGETR v2 shared data package
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.11.0
  flutter: '>=3.41.0'

dependencies:
  flutter:
    sdk: flutter
  shared_core:
    path: ../shared_core
  shared_domain:
    path: ../shared_domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
