create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

do $$
begin
  if not exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where p.proname = 'set_updated_at'
      and n.nspname = 'public'
  ) then
    execute $fn$
      create function public.set_updated_at()
      returns trigger
      language plpgsql
      as $body$
      begin
        new.updated_at = now();
        return new;
      end;
      $body$;
    $fn$;
  end if;
end
$$;

create table if not exists public.dictionary_import_batches (
  id uuid primary key default gen_random_uuid(),
  dataset_version text not null,
  source_file text,
  source_checksum text,
  status text not null default 'running',
  total_rows_read integer not null default 0,
  inserted_rows integer not null default 0,
  updated_rows integer not null default 0,
  duplicate_rows integer not null default 0,
  invalid_rows integer not null default 0,
  empty_meaning_rows integer not null default 0,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  constraint dictionary_import_batches_status_check
    check (status in ('running','completed','failed'))
);

create unique index if not exists ux_dictionary_import_batches_dataset_version
  on public.dictionary_import_batches (dataset_version);

create index if not exists ix_dictionary_import_batches_status_started_at
  on public.dictionary_import_batches (status, started_at desc);

create table if not exists public.dictionary_entries (
  id uuid primary key default gen_random_uuid(),
  seq_id bigint generated by default as identity,
  en_word text not null,
  en_word_normalized text not null,
  search_key text not null,
  pos text,
  raw_pos text,
  tr_meaning text not null,
  meaning_short text,
  source text not null default 'excel_import',
  is_active boolean not null default true,
  import_batch_id uuid references public.dictionary_import_batches(id) on delete set null,
  hash text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dictionary_entries_en_word_not_blank check (length(btrim(en_word)) > 0),
  constraint dictionary_entries_en_word_normalized_not_blank check (length(btrim(en_word_normalized)) > 0),
  constraint dictionary_entries_search_key_not_blank check (length(btrim(search_key)) > 0),
  constraint dictionary_entries_tr_meaning_not_blank check (length(btrim(tr_meaning)) > 0),
  constraint dictionary_entries_hash_not_blank check (length(btrim(hash)) > 0)
);

create unique index if not exists ux_dictionary_entries_seq_id
  on public.dictionary_entries (seq_id);

create unique index if not exists ux_dictionary_entries_hash
  on public.dictionary_entries (hash);

create index if not exists ix_dictionary_entries_en_word_normalized
  on public.dictionary_entries (en_word_normalized);

create index if not exists ix_dictionary_entries_search_key
  on public.dictionary_entries (search_key);

create index if not exists ix_dictionary_entries_en_word
  on public.dictionary_entries (en_word);

create index if not exists ix_dictionary_entries_active_norm
  on public.dictionary_entries (is_active, en_word_normalized);

create index if not exists ix_dictionary_entries_en_word_trgm
  on public.dictionary_entries using gin (en_word gin_trgm_ops);

create index if not exists ix_dictionary_entries_en_word_norm_trgm
  on public.dictionary_entries using gin (en_word_normalized gin_trgm_ops);

create index if not exists ix_dictionary_entries_import_batch_id
  on public.dictionary_entries (import_batch_id);

drop trigger if exists trg_dictionary_entries_updated_at on public.dictionary_entries;
create trigger trg_dictionary_entries_updated_at
before update on public.dictionary_entries
for each row execute function public.set_updated_at();

create table if not exists public.dictionary_fallback_cache (
  id uuid primary key default gen_random_uuid(),
  query_text text not null,
  query_normalized text not null,
  source_lang text not null default 'en',
  target_lang text not null default 'tr',
  provider text not null default 'deepl_edge_function',
  translated_text text not null,
  hit_count integer not null default 1,
  last_hit_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dictionary_fallback_cache_hit_count_check check (hit_count >= 1),
  constraint dictionary_fallback_cache_query_not_blank check (length(btrim(query_normalized)) > 0),
  constraint dictionary_fallback_cache_translation_not_blank check (length(btrim(translated_text)) > 0),
  constraint ux_dictionary_fallback_cache_unique
    unique (query_normalized, source_lang, target_lang, provider)
);

create index if not exists ix_dictionary_fallback_cache_query_normalized
  on public.dictionary_fallback_cache (query_normalized);

create index if not exists ix_dictionary_fallback_cache_last_hit_at
  on public.dictionary_fallback_cache (last_hit_at desc);

drop trigger if exists trg_dictionary_fallback_cache_updated_at on public.dictionary_fallback_cache;
create trigger trg_dictionary_fallback_cache_updated_at
before update on public.dictionary_fallback_cache
for each row execute function public.set_updated_at();

create table if not exists public.dictionary_missing_queries (
  id uuid primary key default gen_random_uuid(),
  query_text text not null,
  query_normalized text not null,
  source_lang text not null default 'en',
  target_lang text not null default 'tr',
  occurrence_count integer not null default 1,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dictionary_missing_queries_occurrence_count_check check (occurrence_count >= 1),
  constraint dictionary_missing_queries_query_not_blank check (length(btrim(query_normalized)) > 0),
  constraint ux_dictionary_missing_queries_unique
    unique (query_normalized, source_lang, target_lang)
);

create index if not exists ix_dictionary_missing_queries_query_normalized
  on public.dictionary_missing_queries (query_normalized);

create index if not exists ix_dictionary_missing_queries_last_seen_at
  on public.dictionary_missing_queries (last_seen_at desc);

drop trigger if exists trg_dictionary_missing_queries_updated_at on public.dictionary_missing_queries;
create trigger trg_dictionary_missing_queries_updated_at
before update on public.dictionary_missing_queries
for each row execute function public.set_updated_at();

create or replace function public.dictionary_bootstrap_manifest()
returns table (
  dataset_version text,
  batch_id uuid,
  row_count bigint,
  generated_at timestamptz
)
language sql
stable
as $$
with latest as (
  select b.id, b.dataset_version
  from public.dictionary_import_batches b
  where b.status = 'completed'
  order by b.completed_at desc nulls last, b.started_at desc
  limit 1
)
select
  l.dataset_version,
  l.id as batch_id,
  (select count(*)::bigint from public.dictionary_entries e where e.is_active = true) as row_count,
  now() as generated_at
from latest l
union all
select
  ''::text as dataset_version,
  null::uuid as batch_id,
  0::bigint as row_count,
  now() as generated_at
where not exists (select 1 from latest);
$$;

create or replace function public.dictionary_entries_bootstrap_page(
  p_after_seq_id bigint default 0,
  p_limit integer default 2000
)
returns table (
  seq_id bigint,
  id uuid,
  en_word text,
  en_word_normalized text,
  search_key text,
  pos text,
  tr_meaning text,
  source text,
  updated_at timestamptz
)
language sql
stable
as $$
select
  e.seq_id,
  e.id,
  e.en_word,
  e.en_word_normalized,
  e.search_key,
  e.pos,
  e.tr_meaning,
  e.source,
  e.updated_at
from public.dictionary_entries e
where e.is_active = true
  and e.seq_id > greatest(coalesce(p_after_seq_id, 0), 0)
order by e.seq_id asc
limit least(greatest(coalesce(p_limit, 2000), 1), 5000);
$$;

alter table public.dictionary_import_batches enable row level security;
alter table public.dictionary_entries enable row level security;
alter table public.dictionary_fallback_cache enable row level security;
alter table public.dictionary_missing_queries enable row level security;

grant usage on schema public to anon, authenticated;

grant select on table public.dictionary_import_batches to anon, authenticated;
grant select on table public.dictionary_entries to anon, authenticated;
grant select on table public.dictionary_fallback_cache to anon, authenticated;
grant insert, update on table public.dictionary_fallback_cache to authenticated;
grant select on table public.dictionary_missing_queries to authenticated;
grant insert, update on table public.dictionary_missing_queries to authenticated;

drop policy if exists dictionary_import_batches_select_completed on public.dictionary_import_batches;
create policy dictionary_import_batches_select_completed on public.dictionary_import_batches
for select
to anon, authenticated
using (status = 'completed');

drop policy if exists dictionary_entries_select_active on public.dictionary_entries;
create policy dictionary_entries_select_active on public.dictionary_entries
for select
to anon, authenticated
using (is_active = true);

drop policy if exists dictionary_fallback_cache_select_all on public.dictionary_fallback_cache;
create policy dictionary_fallback_cache_select_all on public.dictionary_fallback_cache
for select
to anon, authenticated
using (true);

drop policy if exists dictionary_fallback_cache_insert_auth on public.dictionary_fallback_cache;
create policy dictionary_fallback_cache_insert_auth on public.dictionary_fallback_cache
for insert
to authenticated
with check (auth.uid() is not null);

drop policy if exists dictionary_fallback_cache_update_auth on public.dictionary_fallback_cache;
create policy dictionary_fallback_cache_update_auth on public.dictionary_fallback_cache
for update
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

drop policy if exists dictionary_missing_queries_select_auth on public.dictionary_missing_queries;
create policy dictionary_missing_queries_select_auth on public.dictionary_missing_queries
for select
to authenticated
using (auth.uid() is not null);

drop policy if exists dictionary_missing_queries_insert_auth on public.dictionary_missing_queries;
create policy dictionary_missing_queries_insert_auth on public.dictionary_missing_queries
for insert
to authenticated
with check (auth.uid() is not null);

drop policy if exists dictionary_missing_queries_update_auth on public.dictionary_missing_queries;
create policy dictionary_missing_queries_update_auth on public.dictionary_missing_queries
for update
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

grant execute on function public.dictionary_bootstrap_manifest() to anon, authenticated;
grant execute on function public.dictionary_entries_bootstrap_page(bigint, integer) to anon, authenticated;
